[package]
name = "neon"
version = "0.1.0"
edition = "2021"
description = "A real-time operating system for ARM Cortex-M or RISC-V microcontrollers"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
#panic-halt = "0.2.0"
alloc-cortex-m = "0.4.4"
lazy_static = { version = "1.5.0", default-features = false, features = ["spin_no_std"] }

[[example]]
name = "basic"
path = "examples/basic.rs"

[target.'cfg(example = "basic")'.dependencies]
#panic-halt = "0.2.0"


[profile.dev]
opt-level = 0
debug = true
#lto = true

[profile.release]
opt-level = 3
