[package]
name = "neon"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
alloc-cortex-m = "0.4.4"
lazy_static = { version = "1.5.0", default-features = false, features = ["spin_no_std"] }


[profile.dev]
opt-level = 0
debug = true
#lto = true

[profile.release]
opt-level = 0
